### ISSUE TITLE
SSL-certificate outdated/webpage not available

### ISSUE THREAD

**Issue by tefracky** [jerrod-lankford/hassgalaxy#9]
Hello,

it seems the SSL-certificate is outdated (end Fri, 21 Oct 2022 13:22:20 GMT) and due to HSTS, the webpage (https://www.hassgalaxy.app) cannot be used. Can you fix it?

Thanks!

**Comment by isommers1** [comment]
Site is down. The issue you referenced redirects back here, so endless loop of reporting.

**Comment by jerrod-lankford** [comment]
Sorry all ill try to fix this but the issue is really two fold. One the cert is expired and i could renew it but as of Nov 31 heroku free tier is going away, which is what the site was hosted on. So i need to find another place to host it to avoid paying 10 bucks a month.

**Comment by jerrod-lankford** [comment]
Alright should be good to go. Shoutout to railway.app!
